# Generated by Django 3.1.7 on 2021-02-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webProject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
